import { productImage } from './icon.js'

// Merchant taxonomy: each category splits into subtypes so shoppers can
// browse, say, Hunter bows or Tenakth outfits specifically.
export const CATEGORY_META = [
  {
    slug: 'bows',
    label: 'Bows',
    subtypes: [
      { slug: 'hunter', label: 'Hunter' },
      { slug: 'sharpshot', label: 'Sharpshot' },
      { slug: 'warrior', label: 'Warrior' },
    ],
  },
  {
    slug: 'outfits',
    label: 'Outfits',
    subtypes: [
      { slug: 'nora', label: 'Nora' },
      { slug: 'carja', label: 'Carja' },
      { slug: 'tenakth', label: 'Tenakth' },
      { slug: 'utaru', label: 'Utaru' },
      { slug: 'banuk', label: 'Banuk' },
      { slug: 'oseram', label: 'Oseram' },
    ],
  },
  {
    slug: 'gadgets',
    label: 'Gadgets',
    subtypes: [
      { slug: 'traversal', label: 'Tools' },
      { slug: 'combat', label: 'Heavy Arms' },
    ],
  },
  {
    slug: 'boosts',
    label: 'Boosts',
    subtypes: [
      { slug: 'potions', label: 'Potions' },
      { slug: 'food', label: 'Food' },
    ],
  },
  {
    slug: 'ammo',
    label: 'Ammo',
    subtypes: [
      { slug: 'arrows', label: 'Arrows' },
      { slug: 'resources', label: 'Resources' },
    ],
  },
]

export const CATEGORIES = CATEGORY_META.map((c) => c.slug)

// Valid subtype slugs per category, for validation.
export const SUBTYPES_BY_CATEGORY = Object.fromEntries(
  CATEGORY_META.map((c) => [c.slug, c.subtypes.map((s) => s.slug)]),
)

// The merchant's seed stock. `price` is the buy cost in metal shards and the
// single source of truth; `stats` holds the rest of the in-world spec sheet.
const SEED = [
  // ============ Bows · Hunter ============
  {
    title: "Death-Seeker's Shadow",
    price: 420,
    category: 'bows',
    subtype: 'hunter',
    image: '/items/hunter-bow-shadow.webp',
    description:
      'A legendary Hunter bow that rewards patience and precision. Bonus damage from cover and against unaware machines makes every opening shot count.',
    rating: { rate: 4.9, count: 412 },
    stats: {
      type: 'Hunter Bow',
      class: 'Ranged weapon',
      effects: 'Advanced Hunter Arrows · Tear',
      perks: '+Stealth Damage · +Draw Speed',
      modSlots: 3,
      source: 'Hunter merchant — Chainscrape',
      valueWhenSold: 112,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'The Sun Scourge',
    price: 390,
    category: 'bows',
    subtype: 'hunter',
    image: '/items/hunter-bow-carja.webp',
    description:
      'Sundom-gold craftsmanship channelled into a swift Hunter bow. Draws fast and burns hot, scourging machines with fire-charged arrows.',
    rating: { rate: 4.8, count: 277 },
    stats: {
      type: 'Hunter Bow',
      class: 'Ranged weapon',
      effects: 'Fire Arrows · Hunter Arrows',
      perks: '+Fire Damage · +Draw Speed',
      modSlots: 3,
      source: 'Sundom trade caravan',
      valueWhenSold: 104,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Tears of the Land-god',
    price: 405,
    category: 'bows',
    subtype: 'hunter',
    image: '/items/quen-hunter-bow.webp',
    description:
      'A revered Quen-forged Hunter bow. Its purgewater arrows wash the machine bloom from your foes and leave them open to the kill.',
    rating: { rate: 4.7, count: 198 },
    stats: {
      type: 'Hunter Bow',
      class: 'Ranged weapon',
      effects: 'Purgewater Arrows · Hunter Arrows',
      perks: '+Purgewater Buildup · +Reload Speed',
      modSlots: 3,
      source: 'Quen diving fleet',
      valueWhenSold: 108,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Nora Hunter Bow',
    price: 75,
    category: 'bows',
    subtype: 'hunter',
    image: '/items/hunter-bow.webp',
    description:
      'A dependable hide-and-wood Hunter bow of plain Nora make. Light, quiet, and quick on the draw — a fine first bow for any tracker.',
    rating: { rate: 4.0, count: 96 },
    stats: {
      type: 'Hunter Bow',
      class: 'Ranged weapon',
      effects: 'Hunter Arrows',
      perks: '+Draw Speed',
      modSlots: 1,
      source: 'Nora trader',
      valueWhenSold: 19,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Tenakth Hunter Bow',
    price: 95,
    category: 'bows',
    subtype: 'hunter',
    image: '/items/ornate-hunter-bow.webp',
    description:
      'A war-painted Tenakth Hunter bow bristling with bladed accents. Sturdier limbs trade a touch of speed for extra bite.',
    rating: { rate: 4.2, count: 84 },
    stats: {
      type: 'Hunter Bow',
      class: 'Ranged weapon',
      effects: 'Hunter Arrows · Tear',
      perks: '+Tear Damage',
      modSlots: 2,
      source: 'Tenakth trader',
      valueWhenSold: 24,
      fullyUpgraded: 'No',
    },
  },
  // ============ Bows · Sharpshot ============
  {
    title: 'Forgefall',
    price: 480,
    category: 'bows',
    subtype: 'sharpshot',
    image: '/items/sharpshot-bow.webp',
    description:
      'A legendary Sharpshot bow built for the long game. Tearblast and advanced precision arrows strip components clean off a Thunderjaw from range.',
    rating: { rate: 4.9, count: 351 },
    stats: {
      type: 'Sharpshot Bow',
      class: 'Ranged weapon',
      effects: 'Tearblast · Advanced Precision Arrows',
      perks: '+Tear Damage · +Aim Stability',
      modSlots: 3,
      source: 'Oseram workshop — Scalding Spear',
      valueWhenSold: 128,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: "Iriv's Downfall",
    price: 460,
    category: 'bows',
    subtype: 'sharpshot',
    image: '/items/oseram-sharpshot-bow.webp',
    description:
      'A marksman’s masterwork with reinforced Oseram limbs and a punishing draw. Made for those who answer treachery with a single, perfect shot.',
    rating: { rate: 4.8, count: 164 },
    stats: {
      type: 'Sharpshot Bow',
      class: 'Ranged weapon',
      effects: 'Precision Arrows · Tear',
      perks: '+Precision Damage · +Critical Hit Chance',
      modSlots: 3,
      source: 'Quest reward',
      valueWhenSold: 122,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: "Regalla's Wrath",
    price: 510,
    category: 'bows',
    subtype: 'sharpshot',
    image: '/items/ornate-sharpshot-bow.webp',
    description:
      'Forged in the spirit of the rebel commander. This Sharpshot bow hits with the fury of the uprising — relentless, precise, unforgiving.',
    rating: { rate: 5.0, count: 233 },
    stats: {
      type: 'Sharpshot Bow',
      class: 'Ranged weapon',
      effects: 'Shock Arrows · Tearblast',
      perks: '+Shock Damage · +Tear Damage',
      modSlots: 4,
      source: 'Rebel camp cache',
      valueWhenSold: 136,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Utaru Sharpshot Bow',
    price: 150,
    category: 'bows',
    subtype: 'sharpshot',
    image: '/items/utaru-sharpshot-bow.webp',
    description:
      'A supple reedwood Sharpshot bow grown by Utaru hands. Light and steady, with a long, smooth draw for patient ranged work.',
    rating: { rate: 4.3, count: 112 },
    stats: {
      type: 'Sharpshot Bow',
      class: 'Ranged weapon',
      effects: 'Precision Arrows',
      perks: '+Aim Stability',
      modSlots: 2,
      source: 'Utaru weaver',
      valueWhenSold: 38,
      fullyUpgraded: 'No',
    },
  },
  // ============ Bows · Warrior ============
  {
    title: "Carja's Bane",
    price: 470,
    category: 'bows',
    subtype: 'warrior',
    image: '/items/war-bow-carja.webp',
    description:
      'A legendary Warrior bow remembered from the Red Raids. Delivers multiple elemental draws to overwhelm even heavily armoured machines.',
    rating: { rate: 4.9, count: 188 },
    stats: {
      type: 'Warrior Bow',
      class: 'Ranged weapon',
      effects: 'Fire · Frost · Shock Arrows',
      perks: '+Elemental Buildup · +Draw Speed',
      modSlots: 3,
      source: 'Carja armsmaster',
      valueWhenSold: 125,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Rain of Sparks',
    price: 455,
    category: 'bows',
    subtype: 'warrior',
    image: '/items/oseram-warrior-bow.webp',
    description:
      'A Warrior bow that storms the field with shock. Loose a volley and watch the sparks rain down, chaining stagger across a pack of machines.',
    rating: { rate: 4.8, count: 142 },
    stats: {
      type: 'Warrior Bow',
      class: 'Ranged weapon',
      effects: 'Shock Arrows · Multi-shot',
      perks: '+Shock Buildup · +Magazine Capacity',
      modSlots: 3,
      source: 'Oseram tinker',
      valueWhenSold: 121,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Shadow Warrior Bow',
    price: 160,
    category: 'bows',
    subtype: 'warrior',
    image: '/items/war-bow-shadow.webp',
    description:
      'A Shadow-tier Warrior bow with two elemental draws. A solid all-rounder for hunters stepping up to bigger machines.',
    rating: { rate: 4.4, count: 131 },
    stats: {
      type: 'Warrior Bow',
      class: 'Ranged weapon',
      effects: 'Fire · Shock Arrows',
      perks: '+Elemental Buildup',
      modSlots: 2,
      source: 'Hunter merchant',
      valueWhenSold: 40,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Lodge Warrior Bow',
    price: 175,
    category: 'bows',
    subtype: 'warrior',
    image: '/items/war-bow-lodge.webp',
    description:
      'A finely kept Warrior bow bearing the marks of the Hunters Lodge. Balanced elemental draws for the disciplined marksman.',
    rating: { rate: 4.5, count: 119 },
    stats: {
      type: 'Warrior Bow',
      class: 'Ranged weapon',
      effects: 'Fire · Frost Arrows',
      perks: '+Elemental Buildup · +Draw Speed',
      modSlots: 3,
      source: 'Hunters Lodge',
      valueWhenSold: 44,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Nora Warrior Bow',
    price: 110,
    category: 'bows',
    subtype: 'warrior',
    image: '/items/war-bow.webp',
    description:
      'A plain but rugged Nora Warrior bow. A single elemental draw and dependable build for hunters defending the Sacred Land.',
    rating: { rate: 4.1, count: 88 },
    stats: {
      type: 'Warrior Bow',
      class: 'Ranged weapon',
      effects: 'Fire Arrows',
      perks: '+Elemental Buildup',
      modSlots: 1,
      source: 'Nora trader',
      valueWhenSold: 28,
      fullyUpgraded: 'No',
    },
  },
  // ============ Outfits · Nora ============
  {
    title: 'Nora Brave Armor',
    price: 110,
    category: 'outfits',
    subtype: 'nora',
    image: '/items/nora-brave.webp',
    description:
      'Rugged hide-and-bone armour of the Nora hunters. Balanced protection for those who walk the Sacred Land and beyond.',
    rating: { rate: 4.3, count: 204 },
    stats: {
      type: 'Outfit',
      class: 'Light Armor',
      effects: 'Melee + Ranged Defense',
      perks: '+Stealth',
      modSlots: 3,
      source: 'Nora trader',
      valueWhenSold: 28,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Nora Thornmarsh Garb',
    price: 95,
    category: 'outfits',
    subtype: 'nora',
    image: '/items/nora-anointed.webp',
    description:
      'Anointed Nora attire layered for the marsh and the hunt. Favoured by scouts ranging the Daunt’s edges.',
    rating: { rate: 4.1, count: 88 },
    stats: {
      type: 'Outfit',
      class: 'Light Armor',
      effects: 'Ranged Defense',
      perks: '+Stamina',
      modSlots: 2,
      source: 'Daunt trader — Chainscrape',
      valueWhenSold: 24,
      fullyUpgraded: 'No',
    },
  },
  // ============ Outfits · Carja ============
  {
    title: 'Carja Stormranger',
    price: 130,
    category: 'outfits',
    subtype: 'carja',
    image: '/items/carja-stormranger.webp',
    description:
      'Plated Sundom ranger attire of woven mail and gold. Favoured by Carja vanguard for resilience against ranged attacks.',
    rating: { rate: 4.5, count: 167 },
    stats: {
      type: 'Outfit',
      class: 'Medium Armor',
      effects: 'Ranged Defense',
      perks: '+Ranged Resistance',
      modSlots: 3,
      source: 'Carja trader',
      valueWhenSold: 33,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Carja Blazon',
    price: 120,
    category: 'outfits',
    subtype: 'carja',
    image: '/items/carja-blazon.webp',
    description:
      'Light Carja blazon attire dyed in Sundom indigo and gold. Quick and protective for skirmishers who fight on the move.',
    rating: { rate: 4.3, count: 121 },
    stats: {
      type: 'Outfit',
      class: 'Light Armor',
      effects: 'Ranged Defense',
      perks: '+Stealth',
      modSlots: 3,
      source: 'Carja trader',
      valueWhenSold: 31,
      fullyUpgraded: 'No',
    },
  },
  // ============ Outfits · Tenakth ============
  {
    title: 'Tenakth Vindicator',
    price: 175,
    category: 'outfits',
    subtype: 'tenakth',
    image: '/items/tenakth-vindicator.webp',
    description:
      'Painted vindicator plate of the Tenakth clans. Built for the front line, it shrugs off melee blows from charging machines.',
    rating: { rate: 4.8, count: 142 },
    stats: {
      type: 'Outfit',
      class: 'Heavy Armor',
      effects: 'Melee Defense',
      perks: '+Melee Resistance · +Low Health Damage',
      modSlots: 4,
      source: 'Tenakth trader',
      valueWhenSold: 46,
      fullyUpgraded: 'No',
    },
  },
  // ============ Outfits · Utaru ============
  {
    title: 'Utaru Cradlekeeper Robes',
    price: 150,
    category: 'outfits',
    subtype: 'utaru',
    image: '/items/utaru-whisperer.webp',
    description:
      'Earthen robes of the Utaru tenders. Light and resonant, attuned to the great Land-Gods and the rhythms of the soil.',
    rating: { rate: 4.2, count: 98 },
    stats: {
      type: 'Outfit',
      class: 'Light Armor',
      effects: 'Elemental Defense',
      perks: '+Health Regeneration',
      modSlots: 3,
      source: 'Utaru trader',
      valueWhenSold: 39,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Utaru Protector',
    price: 160,
    category: 'outfits',
    subtype: 'utaru',
    image: '/items/utaru-protector.webp',
    description:
      'Sturdy Utaru protector garb reinforced with woven plate. For tenders who must guard the harvest and the herd.',
    rating: { rate: 4.4, count: 90 },
    stats: {
      type: 'Outfit',
      class: 'Medium Armor',
      effects: 'Melee + Ranged Defense',
      perks: '+Health',
      modSlots: 3,
      source: 'Utaru trader',
      valueWhenSold: 41,
      fullyUpgraded: 'No',
    },
  },
  // ============ Outfits · Banuk ============
  {
    title: 'Banuk Ice Hunter',
    price: 140,
    category: 'outfits',
    subtype: 'banuk',
    image: '/items/banuk-ice-hunter.webp',
    description:
      'Banuk ice-hunter garb from the frozen north. Layered against the cold and built for the long, silent hunt.',
    rating: { rate: 4.5, count: 103 },
    stats: {
      type: 'Outfit',
      class: 'Light Armor',
      effects: 'Frost Resistance',
      perks: '+Stealth · +Stamina',
      modSlots: 3,
      source: 'Banuk trader',
      valueWhenSold: 36,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Banuk Trailblazer',
    price: 170,
    category: 'outfits',
    subtype: 'banuk',
    image: '/items/banuk-trailblazer.webp',
    description:
      'Heavy Banuk trailblazer plate of machine-bone and fur. Built to brave blizzards and the werak’s wildest hunts.',
    rating: { rate: 4.6, count: 95 },
    stats: {
      type: 'Outfit',
      class: 'Heavy Armor',
      effects: 'Frost + Melee Defense',
      perks: '+Melee Resistance',
      modSlots: 4,
      source: 'Banuk werak',
      valueWhenSold: 44,
      fullyUpgraded: 'No',
    },
  },
  // ============ Outfits · Oseram ============
  {
    title: 'Oseram Wayfarer',
    price: 120,
    category: 'outfits',
    subtype: 'oseram',
    image: '/items/oseram-wayfarer.webp',
    description:
      'Practical Oseram wayfarer clothes with a tinker’s tool-belt. Hard-wearing and pocketed for the long road.',
    rating: { rate: 4.2, count: 110 },
    stats: {
      type: 'Outfit',
      class: 'Light Armor',
      effects: 'Ranged Defense',
      perks: '+Carry Capacity',
      modSlots: 2,
      source: 'Oseram trader',
      valueWhenSold: 30,
      fullyUpgraded: 'No',
    },
  },
  // ============ Gadgets · Tools ============
  {
    title: 'Echo Shell',
    price: 90,
    category: 'gadgets',
    subtype: 'traversal',
    image: '/items/echo-shell.webp',
    description:
      'A salvaged signalling device that mimics machine calls. Lure a lone machine away from the herd and strike it on your terms.',
    rating: { rate: 4.4, count: 128 },
    stats: {
      type: 'Echo Shell',
      class: 'Field tool',
      effects: 'Lure machines',
      perks: '—',
      modSlots: 0,
      source: 'Quen salvage',
      valueWhenSold: 22,
      fullyUpgraded: '—',
    },
  },
  // ============ Gadgets · Heavy Arms ============
  {
    title: 'The Tie That Binds',
    price: 340,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/ropecaster-lodge.webp',
    description:
      'A legendary Ropecaster of Lodge make. Fires anchored tether lines to pin machines down — hold a Sawtooth still long enough to land the killing blow.',
    rating: { rate: 4.6, count: 158 },
    stats: {
      type: 'Ropecaster',
      class: 'Specialty weapon',
      effects: 'Tie-down Ropes',
      perks: '+Rope Strength · +Reload Speed',
      modSlots: 3,
      source: 'Hunters Lodge',
      valueWhenSold: 90,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: "Ancestor's Return",
    price: 410,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/shredder-gauntlet.webp',
    description:
      'A legendary Shredder Gauntlet. Hurl a returning blade and catch it for a charged throw — chain the rhythm for devastating sustained damage.',
    rating: { rate: 4.8, count: 149 },
    stats: {
      type: 'Shredder Gauntlet',
      class: 'Heavy weapon',
      effects: 'Tear · Catch-combo',
      perks: '+Shredder Damage · +Catch Window',
      modSlots: 3,
      source: 'Quen salvage fleet',
      valueWhenSold: 109,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'The Skykiller',
    price: 520,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/spike-thrower.webp',
    description:
      'A legendary Spike Thrower. Launches heavy explosive spikes that crack the armour of the largest machines — and bring fliers out of the sky.',
    rating: { rate: 5.0, count: 121 },
    stats: {
      type: 'Spike Thrower',
      class: 'Heavy weapon',
      effects: 'Explosive Spikes · Tear',
      perks: '+Explosive Damage · +Reload Speed',
      modSlots: 3,
      source: 'Tenakth armory',
      valueWhenSold: 138,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Ropecaster',
    price: 120,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/ropecaster.webp',
    description:
      'A standard Ropecaster for tying machines to the ground. Less rope tension than a legendary make, but reliable and cheap to maintain.',
    rating: { rate: 4.2, count: 142 },
    stats: {
      type: 'Ropecaster',
      class: 'Specialty weapon',
      effects: 'Tie-down Ropes',
      perks: '+Reload Speed',
      modSlots: 2,
      source: 'Hunter merchant',
      valueWhenSold: 30,
      fullyUpgraded: 'No',
    },
  },
  {
    title: 'Sling',
    price: 110,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/sling.webp',
    description:
      'A bomb-lobbing Sling that arcs elemental pouches onto clustered machines. Mind the fuse — and the blast radius.',
    rating: { rate: 4.3, count: 117 },
    stats: {
      type: 'Sling',
      class: 'Specialty weapon',
      effects: 'Fire · Shock Bombs',
      perks: '+Blast Radius',
      modSlots: 2,
      source: 'Oseram tinker',
      valueWhenSold: 28,
      fullyUpgraded: 'No',
    },
  },
  {
    title: "Sylens's Lance",
    price: 300,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/sylens-lance.webp',
    description:
      'A scavenger’s spear of Old-One alloy, humming with a faint Focus glow. Balanced for swift, lethal melee against unwary foes.',
    rating: { rate: 4.7, count: 88 },
    stats: {
      type: 'Lance',
      class: 'Melee weapon',
      effects: 'Impact · Bleed',
      perks: '+Melee Damage · +Reach',
      modSlots: 2,
      source: 'Mysterious benefactor',
      valueWhenSold: 80,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Forgefire',
    price: 430,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/forgefire.webp',
    description:
      'A legendary Firespitter. Spew a continuous gout of flame to melt frozen machines and ignite anything that draws too close.',
    rating: { rate: 4.7, count: 134 },
    stats: {
      type: 'Firespitter',
      class: 'Heavy weapon',
      effects: 'Continuous Fire',
      perks: '+Fire Damage · +Fuel Tank',
      modSlots: 3,
      source: 'Oseram forge',
      valueWhenSold: 114,
      fullyUpgraded: 'Yes',
    },
  },
  {
    title: 'Oseram Boltblaster',
    price: 540,
    category: 'gadgets',
    subtype: 'combat',
    image: '/items/boltblaster.webp',
    description:
      'A heavy Oseram Boltblaster that spins up to unleash a torrent of bolts. Sustained firepower to grind down the toughest machines.',
    rating: { rate: 4.8, count: 126 },
    stats: {
      type: 'Boltblaster',
      class: 'Heavy weapon',
      effects: 'Rapid Bolts · Tear',
      perks: '+Fire Rate · +Reload Speed',
      modSlots: 3,
      source: 'Oseram forge',
      valueWhenSold: 144,
      fullyUpgraded: 'Yes',
    },
  },
  // ============ Boosts · Potions ============
  {
    title: 'Health Potion',
    price: 15,
    category: 'boosts',
    subtype: 'potions',
    image: '/items/health-potion.webp',
    description:
      'Concentrated medicinal brew that knits wounds in moments. No traveller should leave the settlement without a few.',
    rating: { rate: 4.1, count: 412 },
    stats: {
      type: 'Consumable',
      class: 'Potion',
      effects: 'Restore Health',
      perks: '—',
      modSlots: '—',
      source: 'Apothecary',
      valueWhenSold: 4,
      fullyUpgraded: '—',
    },
  },
  // ============ Boosts · Food ============
  {
    title: 'Roast Turkey Leg',
    price: 8,
    category: 'boosts',
    subtype: 'food',
    image: '/items/turkey.webp',
    description:
      'A hearty roast turkey leg, crisp-skinned and hot off the spit. Filling fare to keep a traveller’s strength up on the trail.',
    rating: { rate: 4.0, count: 188 },
    stats: {
      type: 'Consumable',
      class: 'Food',
      effects: 'Restore Health',
      perks: '—',
      modSlots: '—',
      source: 'Cook',
      valueWhenSold: 2,
      fullyUpgraded: '—',
    },
  },
  {
    title: 'Charred Boar Skewer',
    price: 10,
    category: 'boosts',
    subtype: 'food',
    image: '/items/boar.webp',
    description:
      'Fire-roasted boar seasoned with foraged herbs. A hot meal that restores a traveller’s spirits around the campfire.',
    rating: { rate: 4.2, count: 176 },
    stats: {
      type: 'Consumable',
      class: 'Food',
      effects: 'Restore Health over time',
      perks: '—',
      modSlots: '—',
      source: 'Cook',
      valueWhenSold: 3,
      fullyUpgraded: '—',
    },
  },
  {
    title: 'Rabbit Stew',
    price: 9,
    category: 'boosts',
    subtype: 'food',
    image: '/items/rabbit.webp',
    description:
      'Hearty rabbit stew simmered with foraged roots. A warm bowl that restores vigour and steadies the nerves.',
    rating: { rate: 4.1, count: 142 },
    stats: {
      type: 'Consumable',
      class: 'Food',
      effects: 'Restore Health over time',
      perks: '—',
      modSlots: '—',
      source: 'Cook',
      valueWhenSold: 2,
      fullyUpgraded: '—',
    },
  },
  // ============ Ammo · Arrows ============
  {
    title: 'Hunter Arrows',
    price: 25,
    category: 'ammo',
    subtype: 'arrows',
    image: '/items/hunter-arrow.webp',
    description:
      'A bundle of versatile Hunter arrows — the dependable mainstay for any bow and any quarry.',
    rating: { rate: 4.2, count: 320 },
    stats: {
      type: 'Hunter Arrows',
      class: 'Ammunition',
      effects: 'Impact · Tear',
      perks: '—',
      modSlots: '—',
      source: 'Hunter merchant',
      valueWhenSold: 6,
      fullyUpgraded: '—',
    },
  },
  {
    title: 'Fire Arrows',
    price: 35,
    category: 'ammo',
    subtype: 'arrows',
    image: '/items/fire-arrow.webp',
    description:
      'Pitch-tipped Fire arrows that set machines and brush ablaze. Stack the burn to melt through armour.',
    rating: { rate: 4.4, count: 241 },
    stats: {
      type: 'Fire Arrows',
      class: 'Ammunition',
      effects: 'Fire Buildup',
      perks: '—',
      modSlots: '—',
      source: 'Hunter merchant',
      valueWhenSold: 9,
      fullyUpgraded: '—',
    },
  },
  {
    title: 'Tearblast Arrows',
    price: 45,
    category: 'ammo',
    subtype: 'arrows',
    image: '/items/tearblast-arrow.webp',
    description:
      'Concussive Tearblast arrows that rip components off machines in a single burst. A salvager’s favourite.',
    rating: { rate: 4.6, count: 207 },
    stats: {
      type: 'Tearblast Arrows',
      class: 'Ammunition',
      effects: 'Tear Burst',
      perks: '—',
      modSlots: '—',
      source: 'Hunter merchant',
      valueWhenSold: 12,
      fullyUpgraded: '—',
    },
  },
  // ============ Ammo · Resources ============
  {
    title: 'Blaze',
    price: 20,
    category: 'ammo',
    subtype: 'resources',
    image: '/items/blaze.webp',
    description:
      'A canister of Blaze — volatile machine fuel. The raw stuff of fire arrows, bombs, and a warm camp on a cold night.',
    rating: { rate: 4.0, count: 264 },
    stats: {
      type: 'Resource',
      class: 'Crafting fuel',
      effects: 'Fire crafting component',
      perks: '—',
      modSlots: '—',
      source: 'Salvaged from machines',
      valueWhenSold: 5,
      fullyUpgraded: '—',
    },
  },
  {
    title: 'Chillwater',
    price: 22,
    category: 'ammo',
    subtype: 'resources',
    image: '/items/chillwater.webp',
    description:
      'A sealed flask of Chillwater — supercooled machine coolant. The key ingredient for frost ammo and brimstone-cold traps.',
    rating: { rate: 4.0, count: 198 },
    stats: {
      type: 'Resource',
      class: 'Crafting fluid',
      effects: 'Frost crafting component',
      perks: '—',
      modSlots: '—',
      source: 'Salvaged from machines',
      valueWhenSold: 6,
      fullyUpgraded: '—',
    },
  },
]

export function buildInventory() {
  return SEED.map((p, i) => ({
    id: i + 1,
    ...p,
    // Use a real image when one is supplied, else a generated themed SVG.
    image: p.image || productImage(p.category),
  }))
}
